# Generated by Django 5.0.3 on 2024-03-20 23:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='apellido',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nombre',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='motivo',
            field=models.TextField(default='Vacaciones'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='Esta es la respuesta.'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default='¿Cuál es tu pregunta?'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(default='Contenido de la política.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(default='Título de la Política', max_length=255),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.CharField(default='Tipo de Beneficio', max_length=100)),
                ('descripcion', models.TextField(default='Descripción del beneficio.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.employee')),
            ],
        ),
    ]
