# Generated by Django 5.0.3 on 2024-03-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_remove_employee_name_remove_vacationrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='tipo_beneficio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='motivo',
            field=models.TextField(),
        ),
    ]
