# Generated by Django 5.0.3 on 2024-03-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_beneficio_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
