# Generated by Django 5.0.3 on 2024-03-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_delete_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacationRequest',
            new_name='vacaciones',
        ),
    ]
