# Generated by Django 5.0.3 on 2024-03-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_rename_vacationrequest_vacaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Personal',
        ),
        migrations.RenameField(
            model_name='beneficio',
            old_name='employee',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='nomina',
            old_name='employee',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='vacaciones',
            old_name='employee',
            new_name='personal',
        ),
    ]
