# Generated by Django 5.0.3 on 2024-03-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_rename_employee_personal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='beneficio',
            old_name='personal',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='nomina',
            old_name='personal',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='vacaciones',
            old_name='personal',
            new_name='employee',
        ),
    ]
