# Generated by Django 5.0.3 on 2024-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_rename_personal_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departamento',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='puesto',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
