# Generated by Django 5.0.3 on 2024-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_employee_departamento_employee_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numero',
            field=models.CharField(default='', max_length=100),
        ),
    ]
