# Generated by Django 5.0.3 on 2024-05-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_employee_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='dias_de_vacaciones',
            field=models.CharField(default='', max_length=100),
        ),
    ]
