# Generated by Django 5.0.3 on 2024-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_vacaciones_dias_de_vacaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='numero',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='dias_de_vacaciones_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
