# Generated by Django 5.0.3 on 2024-05-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0011_rename_numero_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='pago',
            field=models.CharField(default='', max_length=100),
        ),
    ]
