# Generated by Django 5.0.3 on 2024-05-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0013_rename_pago_nomina_bonificaciones_nomina_deducciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='total_descuentos',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='total_devengado',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='total_ingresos',
        ),
        migrations.AlterField(
            model_name='nomina',
            name='bonificaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='deducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='otros_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='pension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
