# Generated by Django 5.0.3 on 2024-05-05 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0014_remove_nomina_total_descuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nomina',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
