# Generated by Django 5.0.3 on 2024-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_nomina_end_date_nomina_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
