# Generated by Django 5.0.3 on 2024-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0016_alter_nomina_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
